### ISSUE TITLE
Adding "RUN chmod +x /entrypoint.sh" to Dockerfile

### ISSUE THREAD

**Issue by xigyou** [aciobanu/docker-scrapy#2]
I get the error when I build from the Dockerfile
container_linux.go:247: starting container process caused "exec: \"/runtime/entrypoint.sh\": permission denied"

need  add this to Dockerfile 

**RUN chmod +x /runtime/entrypoint.sh**

**Comment by aciobanu** [comment]
Hi @xigyou,

Thanks for the report, I'll take a look. Are you, by any chance, using Windows or a filesystem that doesn't support the traditional Unix permissions?

Thanks

**Comment by xigyou** [comment]
I  use Docker on Mac

**Comment by xigyou** [comment]
just  wget the Dockerfile and entrypoint.sh.   
then build.

**Comment by aciobanu** [comment]
OK, I understand. That should work now. In general, you're better off cloning the repository with `git clone https://github.com/aciobanu/docker-scrapy.git` rather than wget-ing.

**Comment by xigyou** [comment]
Yes, thank you!
