### ISSUE TITLE
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by cornelyus** [aciobanu/docker-scrapy#5]
Hi,

A long time ago I used your Dockerfile to build a new image for a use case I have.. just need a couple more python packages..
One of those python packages stopped working and I wanted to upgrade.. but there's an error doing dockerbuild with my Docker file..

So I checked your last one, did a dockerbuild also and the error of "ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly" is also showing..

Can you help?

I would be glad just to upgrade the gspread package with pip, but that seems to not be the best way to change on a Docker Image..

Thanks in advance.

**Comment by aciobanu** [comment]
Hi,

I've fixed the image build and also pushed a new tag, 2.5.0; looks like `cryptography` requires Rust now..

Cheers
